dil-classroom/projet-dilemme

src/main/java/ch/heigvd/dil/Main.java, src/main/java/ch/heigvd/dil/cli_cmds/BuildCmd.java, src/main/java/ch/heigvd/dil/cli_cmds/CleanCmd.java, src/main/java/ch/heigvd/dil/cli_cmds/NewCmd.java, src/main/java/ch/heigvd/dil/cli_cmds/ServeCmd.java
=> Issue #16 - Format files with google-java-format

pom.xml, src/main/java/ch/heigvd/dil/utils/parsers/MarkdownParser.java
=> Issue #23 - Create a Markdown parser

src/main/java/ch/heigvd/dil/utils/parsers/PageContentSeparator.java, src/test/java/ch/heigvd/dil/utils/parsers/PageContentSeparatorTest.java
Here is a proposition for page parser implementation. The only goal of the class I added is to separate the content from de config. I didn't write a static class because I didn't want to return an array of two  elements with a function. I prefer parse with the constructor and then put the result in two strings that can be get back with geters.
Another question that we must discuss is how to handle the user errors, I mean when the source content is badly formatted. My proposition is to throw a ParseException that would be handle by the caller.
=> add and implements PageContentSeparator with simple test

site/config.json, site/content/page.md
=> fill example files

src/main/java/ch/heigvd/dil/data_structures/Page.java, src/main/java/ch/heigvd/dil/data_structures/Site.java, src/main/java/ch/heigvd/dil/utils/HTMLSiteGenerator.java
Close #22.
Only the Page data structure is needed for this sprint (sprint 1).
=> Issue #22 - Create data structures

.github/workflows/format.yml, .github/workflows/maven.yml, src/main/java/ch/heigvd/dil/cli_cmds/BuildCmd.java, src/main/java/ch/heigvd/dil/cli_cmds/CleanCmd.java, src/main/java/ch/heigvd/dil/cli_cmds/NewCmd.java, src/main/java/ch/heigvd/dil/cli_cmds/ServeCmd.java, src/main/java/ch/heigvd/dil/cli_cmds/VersionCmd.java, src/main/java/ch/heigvd/dil/data_structures/Site.java, src/main/java/ch/heigvd/dil/utils/HTMLSiteGenerator.java, src/main/java/ch/heigvd/dil/utils/parsers/MarkdownParser.java, src/test/java/ch/heigvd/dil/AppTest.java, src/test/java/ch/heigvd/dil/utils/parsers/PageContentSeparatorTest.java
=> Fix Issue #36 - Add Github Integration

pom.xml
Close #38
I choosed to use handlebars motor.
=> Issue #38 - Choose and add a templating motor

src/main/java/ch/heigvd/dil/cli_cmds/BuildCmd.java, src/main/java/ch/heigvd/dil/cli_cmds/ServeCmd.java
=> Issue #45 - Add serve command

src/test/java/ch/heigvd/dil/cli_cmds/BuildCmdTest.java, src/test/java/ch/heigvd/dil/cli_cmds/CleanCmdTest.java, src/test/java/ch/heigvd/dil/cli_cmds/InitCmdTest.java, src/test/java/ch/heigvd/dil/cli_cmds/TestUtils.java
=> Issue #62 - Add integration tests

src/main/java/ch/heigvd/dil/cli_cmds/BuildCmd.java, src/main/java/ch/heigvd/dil/cli_cmds/CleanCmd.java, src/main/java/ch/heigvd/dil/cli_cmds/InitCmd.java, src/main/java/ch/heigvd/dil/cli_cmds/ServeCmd.java, src/main/java/ch/heigvd/dil/cli_cmds/VersionCmd.java
=> Issue #79 - Copy media files when building

.gitignore, pom.xml, site/build/index.html, src/main/java/ch/heigvd/dil/cli_cmds/BuildCmd.java, src/main/java/ch/heigvd/dil/data_structures/Site.java, src/main/java/ch/heigvd/dil/utils/TemplateInjector.java, src/main/resources/template/default_page.html, src/test/java/ch/heigvd/dil/cli_cmds/BuildCmdTest.java, src/test/java/ch/heigvd/dil/data_structures/PageTest.java, src/test/java/ch/heigvd/dil/utils/TemplateInjectorTest.java, src/test/resources/testFiles/test-template/layout-valid.html
=> Issue #41 - Inject Page properties

.github/workflows/release.yml, pom.xml
=> Issue #86 - rename project into dilemme

pom.xml, src/main/java/ch/heigvd/dil/Main.java, src/main/java/ch/heigvd/dil/cli_cmds/ServeCmd.java
=> Issue #84 Implement serve command

src/test/java/ch/heigvd/dil/utils/TemplateInjectorTest.java
=> Issue #40 - Inject site properties

pom.xml
=> Issue #71 - Configure Jacoco

src/main/java/ch/heigvd/dil/utils/Resources.java, src/main/java/ch/heigvd/dil/utils/TemplateInjector.java, src/main/java/ch/heigvd/dil/utils/parsers/ConfigGenerator.java
=> Issue #95 - Move `getResource` methods into a new class

src/main/java/ch/heigvd/dil/utils/Resources.java, src/test/java/ch/heigvd/dil/utils/ResourcesTest.java, src/test/resources/testFiles/test-resources/resource_with_EOL.txt, src/test/resources/testFiles/test-resources/resource_without_EOL.txt
=> Issue #97 - Fix `getResources` doesn't append end of lines

site/build/index.html, src/main/java/ch/heigvd/dil/cli_cmds/BuildCmd.java, src/main/java/ch/heigvd/dil/utils/TemplateInjector.java, src/test/java/ch/heigvd/dil/utils/TemplateInjectorTest.java, src/test/resources/valid-site/config.json, src/test/resources/valid-site/index.md, src/test/resources/valid-site/template/layout.html, src/test/resources/valid-site/template/menu.html
=> Issue #42 - Include content of HTML template files

pom.xml
=> Issue #92 - Fix maven jar with dependencies

site/build/index.html, site/build/template/menu.html, site/template/layout.html, site/template/menu.html, src/main/java/ch/heigvd/dil/cli_cmds/BuildCmd.java, src/main/java/ch/heigvd/dil/utils/TemplateInjector.java
=> Issue #59 - Integrate template engine in `BuildCmd`

pom.xml, src/main/java/ch/heigvd/dil/benchmarks/BenchmarkList.java
=> Issue #73 - Use JMH to measure performances

src/main/java/ch/heigvd/dil/utils/FileHandler.java, src/main/java/ch/heigvd/dil/utils/Resources.java
=> Issue #107 - Fix resource leak

src/main/java/ch/heigvd/dil/data_structures/Page.java, src/main/java/ch/heigvd/dil/data_structures/Site.java, src/main/java/ch/heigvd/dil/utils/TemplateInjector.java
=> Issue #106 - Clean `Page` and `Site` datastructures

site/build/index.html, site/template/layout.html
=> Issue #111 - Fix `layout.html` contains incorrect variables

src/main/java/ch/heigvd/dil/cli_cmds/BuildCmd.java, src/main/java/ch/heigvd/dil/utils/TemplateInjector.java
=> Issue #115 - Remove unnecessary functions / variables

README.md
=> Issue #118 - correct user manual

pom.xml, src/main/java/ch/heigvd/dil/cli_cmds/BuildCmd.java, src/main/resources/schema/page-config-schema.json, src/main/resources/schema/site-config-schema.json
=> Issue #119 - improve error handling

src/main/java/ch/heigvd/dil/Version.java
=> Issue #117 - Update version
